using System.Net;
using System.Net.Http.Json;
using System.Security.Claims;
using System.Text.Json;
using System.Text.RegularExpressions;
using FluentAssertions;
using InsureEdge.API.Controllers;
using InsureEdge.API.Services;
using InsureEdge.Application.Interfaces;
using InsureEdge.Domain.Entities;
using InsureEdge.Infrastructure.Data;
using InsureEdge.Infrastructure.Identity;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Npgsql;
using Xunit;
using Claim = System.Security.Claims.Claim;

namespace InsureEdge.UnitTests;

// Opt-in test against a dedicated temporary cluster, never application configuration.
// Start PostgreSQL on 127.0.0.1:55439 with user producer_test, then set
// INSUREEDGE_LOCAL_PRODUCER_TEST=1. No production connection strings are accepted.
public class ProducerReservationApiTests
{
    private sealed class LocalPostgresFactAttribute : FactAttribute
    {
        public LocalPostgresFactAttribute()
        {
            if (Environment.GetEnvironmentVariable("INSUREEDGE_LOCAL_PRODUCER_TEST") != "1")
                Skip = "Requires the isolated local PostgreSQL test cluster on port 55439.";
        }
    }

    [LocalPostgresFact]
    [Trait("Category", "LocalPostgres")]
    public async Task Real_routes_reserve_sequential_ids_and_save_without_overwriting_existing_producers()
    {
        var database = "producer_verification_" + Guid.NewGuid().ToString("N");
        const string adminConnection = "Host=127.0.0.1;Port=55439;Username=producer_test;Database=postgres;Pooling=false";
        await using var admin = new NpgsqlConnection(adminConnection);
        await admin.OpenAsync();
        await using (var create = new NpgsqlCommand($"CREATE DATABASE {database}", admin))
            await create.ExecuteNonQueryAsync();
        var connection = new NpgsqlConnectionStringBuilder(adminConnection) { Database = database }.ConnectionString;
        try
        {
            var options = new DbContextOptionsBuilder<InsureEdgeDbContext>()
                .UseNpgsql(connection).UseSnakeCaseNamingConvention().Options;
            await using (var db = new InsureEdgeDbContext(options))
            {
                // Use the real EF column definitions for these two tables only.
                var script = db.Database.GenerateCreateScript();
                foreach (var table in new[] { "intermediary", "producer" })
                {
                    var ddl = Regex.Match(script, $@"CREATE TABLE {table} \([\s\S]*?\n\);").Value;
                    ddl.Should().NotBeEmpty();
                    // Match the checked-in PostgreSQL BIGSERIAL schema.
                    ddl = ddl.Replace("bigint GENERATED BY DEFAULT AS IDENTITY", "bigserial");
                    await db.Database.ExecuteSqlRawAsync(ddl);
                }
                db.Intermediaries.Add(new Intermediary { ClientId = 1, IntermediaryCode = "IM00000001", IntermediaryName = "Local verification" });
                await db.SaveChangesAsync();
                db.Producers.Add(new Producer { ClientId = 1, IntermediaryId = 1, ProducerCode = "PR00000001", FirstName = "Existing", LastName = "Producer" });
                await db.SaveChangesAsync();
            }

            var builder = WebApplication.CreateBuilder();
            builder.WebHost.UseUrls("http://127.0.0.1:0");
            builder.Logging.ClearProviders();
            builder.Services.AddDbContext<InsureEdgeDbContext>(o => o.UseNpgsql(connection).UseSnakeCaseNamingConvention());
            builder.Services.AddScoped<ProducerDraftIds>();
            builder.Services.AddHttpContextAccessor();
            builder.Services.AddScoped<ICurrentTenantService, CurrentTenantService>();
            builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie();
            builder.Services.AddAuthorization();
            builder.Services.AddControllers().AddApplicationPart(typeof(DistributionController).Assembly);
            await using var app = builder.Build();
            // Test-only authenticated identity; production authentication is unchanged.
            app.Use(async (ctx, next) =>
            {
                ctx.User = new ClaimsPrincipal(new ClaimsIdentity(new[] {
                    new Claim("client_id", "1"), new Claim(ClaimTypes.NameIdentifier, "1")
                }, "LocalVerification"));
                await next();
            });
            app.UseAuthorization();
            app.MapControllers();
            await app.StartAsync();
            var address = app.Services.GetRequiredService<IServer>().Features.Get<IServerAddressesFeature>()!.Addresses.Single();
            using var http = new HttpClient { BaseAddress = new Uri(address) };
            var drafts = new List<ProducerDraftReservation>();
            for (var i = 2; i <= 4; i++)
            {
                var response = await http.PostAsync("/api/distribution/producers/reserve-id/1", null);
                var body = await response.Content.ReadAsStringAsync();
                response.StatusCode.Should().Be(HttpStatusCode.OK, body);
                var draft = JsonSerializer.Deserialize<ProducerDraftReservation>(body)!;
                draft.ProducerCode.Should().Be("PR" + i.ToString("D8"));
                draft.Token.Should().NotBeNullOrWhiteSpace();
                drafts.Add(draft);
            }
            for (var i = 0; i < 2; i++)
            {
                var request = new { intermediary_id = 1, producer_draft_token = drafts[i].Token,
                    first_name = "Draft" + i, last_name = "Producer", pc_license_requirement = "Combined", plcl_combined_license = "1234567890" };
                var saved = await http.PostAsJsonAsync("/api/distribution/producers", request);
                saved.StatusCode.Should().Be(HttpStatusCode.OK, await saved.Content.ReadAsStringAsync());
                var retry = await http.PostAsJsonAsync("/api/distribution/producers", request);
                retry.StatusCode.Should().Be(HttpStatusCode.OK);
                var row = await http.GetFromJsonAsync<JsonElement>($"/api/distribution/producers/{i + 2}");
                row.GetProperty("producer_code").GetString().Should().Be(drafts[i].ProducerCode);
                row.GetProperty("first_name").GetString().Should().Be("Draft" + i);
            }
            var existing = await http.GetFromJsonAsync<JsonElement>("/api/distribution/producers/1");
            existing.GetProperty("producer_code").GetString().Should().Be("PR00000001");
            var edited = await http.PutAsJsonAsync("/api/distribution/producers/2", new {
                intermediary_id = 1, first_name = "Edited", last_name = "Producer",
                pc_license_requirement = "Combined", plcl_combined_license = "1234567890"
            });
            edited.StatusCode.Should().Be(HttpStatusCode.OK);
            var afterEdit = await http.GetFromJsonAsync<JsonElement>("/api/distribution/producers/2");
            afterEdit.GetProperty("producer_code").GetString().Should().Be(drafts[0].ProducerCode);
            afterEdit.GetProperty("first_name").GetString().Should().Be("Edited");
            var parallel = await Task.WhenAll(Enumerable.Range(0, 3).Select(_ => http.PostAsync("/api/distribution/producers/reserve-id/1", null)));
            var codes = new List<string>();
            foreach (var response in parallel)
            {
                response.StatusCode.Should().Be(HttpStatusCode.OK);
                codes.Add((await response.Content.ReadFromJsonAsync<ProducerDraftReservation>())!.ProducerCode);
            }
            codes.Should().BeEquivalentTo("PR00000005", "PR00000006", "PR00000007");
            await using (var reopened = new InsureEdgeDbContext(options))
            {
                (await reopened.Producers.CountAsync()).Should().Be(3);
                (await reopened.Producers.FindAsync(1L))!.ProducerCode.Should().Be("PR00000001");
            }
            await app.StopAsync();
        }
        finally
        {
            await using var drop = new NpgsqlCommand($"DROP DATABASE {database} WITH (FORCE)", admin);
            await drop.ExecuteNonQueryAsync();
        }
    }
}
